### ISSUE TITLE
unable to get the error messages from the api call

### ISSUE THREAD

**Issue by ilkosta** [malko/node-promised-redmine#11]
When I generate a wrong call, I cannot know where are the errors, but I get a cryptic `STATUSCODE_REJECTION422` .

From the documentation I see the method `(get|set)Verbose(bool) ` to activate console messages, but with no effect.

**Comment by malko** [comment]
In fact you should already get a STATUSCODE REJECTION 422 message because of verbosity turned on. Nevertheless adding the body to the log seems useful so i merged your pull request.
Thanks for your contribution you can npm update right now i've just publish the new version a minute ago.
