### ISSUE TITLE
User Impersonation

### ISSUE THREAD

**Issue by tylershumaker** [malko/node-promised-redmine#13]
I would be a nice feature to utilize user impersonation ( X-Redmine-Switch-User ) for postIssue and updateIssue.

**Comment by malko** [comment]
If we add a possible params property like: redmine.request(method, path, {impersonate: 'usename'} )
would this be ok for you.
You will so be able to add an impersonate param to all methods using request under the hood.

**Comment by malko** [comment]
added in release 0.2.13 by adding an impersonate value to the params argument:
```
var params = {impersonate: "userlogin"};
```

**Comment by tylershumaker** [comment]
I can't get this to work. For example:  updateIssue returns this.put('issues/' + id, {issue:params}).
So in put and request "params.issue.impersonate" would have to be used to get the usernlogin.  Maybe i am not setting something correct with params.  

I also have to set params with retry:1 for every function or i get a TypeError: Cannot read property 'retry' of undefined ... redmine.js:98:20 error since the 0.2.12 release.  I tried calling setMaxTry and setting maxTry in config without luck. 

Sorry I don't have more time to fix the code as I am trying to get a release out the door.

**Comment by malko** [comment]
Hi,

First thank you for reporting. I have no redmine install available for testing and so i'm blind on developing this lib. I'm looking in rewrite tests with nock when i got a little extra time to give it a try.

Nevertheless, can you please try to use the fix-params branch i just pushed, i think it should fix the two mentioned issues. If so i'll publish a new release right away.

Be aware the signature for post / update methods have changed a little (params is now a separate parameter than the item data sent to the server).

regards,

malko

**Comment by malko** [comment]
Finally i reintroduced some unit test using nock.
I spotted some problems arround retry, impersonate and verbose features which all should be gone now.
please update to 0.3.0 version hoping this will be ok for you.
Sorry about the previous buggy version, i'm confident that unit test will avoid such buggy version in the future.

thanks again for reporting!!!

**Comment by tylershumaker** [comment]
0.3.0 fixed the issues i was having with retry and impersonate.  Thanks for the update.
